<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: superuser
 * Date: Thu, 14 Mar 2013 15:38:48 -0700
 */

$conf['title'] = 'Sony Transformation';
$conf['template'] = 'sony';
$conf['license'] = 'cc-zero';
$conf['useheading'] = '1';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['sepchar'] = '-';

// end auto-generated content
